### ISSUE TITLE
Put together a group of Sublime Snippets

### ISSUE THREAD

**Issue by glennabaron** [madebymode/mode-front-end#21]
Kind of a personal to do, but this will make using mode front end a lot easier for anyone. Would include things like: 

- media query includes
- utility includes
- heavily used markup patterns (such as grid combinations)

**Comment by glennabaron** [comment]
Been working on this. Thinking eventually, we could make it a [Sublime Package](https://packagecontrol.io/docs/submitting_a_package) instead of just keeping the files in the repo.

**Comment by tannerhodges** [comment]
Yoooo, so since #36 we're moving all the Sass over to https://github.com/madebymode/mode-sass, I'm thinking we can either:

- Create one repo/package for _all_ of our snippets, or
- Create separate repo/packages for each set of snippets (mode-sass, mode-js, etc.)

What say you?

**Comment by glennabaron** [comment]
Maybe this lives as part of the MFE starter kit?

Right now I have three categories:
1. Minimis-specific things, mostly media queries.
2. Markup patterns you would commonly use with minimis (two column grid, list, etc.). 
3. Another is a quick add for `data-ga-click-event`, which is specific to our analytics package, but it wouldn't really make sense to make a separate package just for that.

I feel like I should make `minimis-snippets`. And maybe leave the other stuff (more MFE-type things like the analytics one) out completely?

**Comment by glennabaron** [comment]
Part of me also thinks these are too opinionated/there may be conflicts with user's existing snippets. 

They are beneficial for me because I have really short trigger names, like simply `md` makes our standard media query @ md:

```
@include mq('md') {
  ${1}
}
```

Which could be conflicting with other snippets? But I think prefixing them all with `minimis-` would take too much time to type out as a trigger, making the whole point of a snippet kind of moot. Now I'm thinking of going back to just having them in a folder in minimis repo and people can add/edit as they please. 🙀 I'm conflicted.

**Comment by tannerhodges** [comment]
Snippets/completions should be specific each package. Eventually, I'd like to try making them part of the repo (e.g., combine minimis and minimis-snippets), but let's start by keeping them separate.

As for prefixing everything with `minimis-`, I agree that's a pain. Don't worry about being too opinionated for now—let's see what we have first.

Start a `minimis-snippets` repo with your existing snippets, post a link in this issue, and let's try it out. 👍

**Comment by glennabaron** [comment]
[Boom](https://github.com/madebymode/minimis-snippets). Here's the few we just talked about IRL. Now at least we have a starting point. I think they could be useful for some people but probably not all. I'll add this to the docs eventually as well.

**Comment by tannerhodges** [comment]
Perfect. Let's keep the conversation going in that repo.

Closing.
